### ISSUE TITLE
Low fingerprint match although correct

### ISSUE THREAD

**Issue by cptpike** [cptpike/linuxhardwareguide#323]
278d86a7569412c4370d3f6b00d0f9
ProLiant Server has 0.78 only?

**Comment by thooge** [comment]
What does 0.78 mean?

**Comment by cptpike** [comment]
The script
https://github.com/cptpike/linuxhardwareguide/blob/master/tools/uploads/scan_hw_upload.pl
analyzes the uploaded hardware scan. It calculates probabilities which defines how much the scanned mainboard corresponds to a mainboard already existing in the database. Currently, this calculation only uses the PCI IDs and Subsystem IDs of the hardware (a.k.a. the "fingerprint" of the mainboard). 

The ProLiant Server reaches only a probability of 0.78 (possible values range from 0 to 1) that it corresponds to the correct entry in the database. Instead, it should be 1 (or nearly 1 due to the fact that the raid modules are not part of the mainboard itself). Therefore, an error seems to be in the algorithm to calculate the fingerprint matching probability.

I assume that it is due to the fact that several components probably have the same PCI ID and that the matching probability only takes unique IDs into account, which reduces the number of possible matchings. But this needs to be investigated further.

**Comment by thooge** [comment]
Ah, ok. One more information according that machine:
Normally the network card is of a special form factor and attached direcly to the mainbord.
This machine has a normal card in an extension slot.
New machine just bought some weeks ago, not ordered a special kind of that card.

**Comment by cptpike** [comment]
Update of list of Subsystem IDs was broken. Fixed.
Probability is not 1.
